### PR TITLE
Update calculator.py - sprina

### PR DESCRIPTION
**Pull request by sprinac**

### CODE REVIEW

**Review by DylanFitzpatrick01 — CHANGES_REQUESTED** [review]
Can you add a test for this function in test.py please?

**Comment by sprinac** [comment]
question: so now do i pull in my github desktop of the main again?

**Comment by sprinac** [comment]
think i just did it there

**Review by penrosed — DISMISSED** [review]
Looks good. Nice work!

**Review by penrosed — CHANGES_REQUESTED** [review]
In order for checks to pass, you need to add a "return x/y" line after the print on line 47.

**Pull request closed without merging**
